services:
  - type: web
    name: api-whatsapp-python-v1
    runtime: python
    rootDir: app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_API_VERSION
        value: v22.0
